stages:
  - build

variables:
  # Interne Registry-IP (Port 5050 auf GitLab VM)
  REGISTRY: 192.168.60.170:5050
  IMAGE_PATH: ${REGISTRY}/darthvaper/docker-proxmox-commander

.docker-build:
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--insecure-registry=192.168.60.170:5050"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    # Warte bis Docker-Daemon bereit ist
    - until docker info; do sleep 2; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY

build-dpc-api:
  extends: .docker-build
  stage: build
  script:
    - docker build -t $IMAGE_PATH/dpc-api:$CI_COMMIT_TAG -t $IMAGE_PATH/dpc-api:latest ./backend
    - docker push $IMAGE_PATH/dpc-api:$CI_COMMIT_TAG
    - docker push $IMAGE_PATH/dpc-api:latest
  rules:
    - if: $CI_COMMIT_TAG

build-dpc-web:
  extends: .docker-build
  stage: build
  script:
    - docker build -t $IMAGE_PATH/dpc-web:$CI_COMMIT_TAG -t $IMAGE_PATH/dpc-web:latest ./frontend
    - docker push $IMAGE_PATH/dpc-web:$CI_COMMIT_TAG
    - docker push $IMAGE_PATH/dpc-web:latest
  rules:
    - if: $CI_COMMIT_TAG
