stages:
  - build

variables:
  REGISTRY: registry.gitlab.newsxc.net
  IMAGE_PATH: ${REGISTRY}/darthvaper/docker-proxmox-commander

.docker-build:
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY

build-dpc-api:
  extends: .docker-build
  stage: build
  script:
    - docker build -t $IMAGE_PATH/dpc-api:$CI_COMMIT_TAG -t $IMAGE_PATH/dpc-api:latest ./backend
    - docker push $IMAGE_PATH/dpc-api:$CI_COMMIT_TAG
    - docker push $IMAGE_PATH/dpc-api:latest
  rules:
    - if: $CI_COMMIT_TAG

build-dpc-web:
  extends: .docker-build
  stage: build
  script:
    - docker build -t $IMAGE_PATH/dpc-web:$CI_COMMIT_TAG -t $IMAGE_PATH/dpc-web:latest ./frontend
    - docker push $IMAGE_PATH/dpc-web:$CI_COMMIT_TAG
    - docker push $IMAGE_PATH/dpc-web:latest
  rules:
    - if: $CI_COMMIT_TAG
