stages:
  - build

variables:
  REGISTRY: registry.newsxc.net
  IMAGE_PATH: ${REGISTRY}/darthvaper/docker-proxmox-commander
  DOCKER_BUILDKIT: "1"

.docker-build:
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - until docker info; do sleep 2; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY

build-dpc-api:
  extends: .docker-build
  stage: build
  script:
    # Cache vom letzten Image laden (ignoriere Fehler falls nicht vorhanden)
    - docker pull $IMAGE_PATH/dpc-api:latest || true
    - docker build
        --cache-from $IMAGE_PATH/dpc-api:latest
        -t $IMAGE_PATH/dpc-api:$CI_COMMIT_TAG
        -t $IMAGE_PATH/dpc-api:latest
        ./backend
    - docker push $IMAGE_PATH/dpc-api:$CI_COMMIT_TAG
    - docker push $IMAGE_PATH/dpc-api:latest
  rules:
    - if: $CI_COMMIT_TAG

build-dpc-web:
  extends: .docker-build
  stage: build
  script:
    # Cache vom letzten Image laden (ignoriere Fehler falls nicht vorhanden)
    - docker pull $IMAGE_PATH/dpc-web:latest || true
    - docker build
        --cache-from $IMAGE_PATH/dpc-web:latest
        -t $IMAGE_PATH/dpc-web:$CI_COMMIT_TAG
        -t $IMAGE_PATH/dpc-web:latest
        ./frontend
    - docker push $IMAGE_PATH/dpc-web:$CI_COMMIT_TAG
    - docker push $IMAGE_PATH/dpc-web:latest
  rules:
    - if: $CI_COMMIT_TAG
